version: 2.1

orbs:
  local:
    jobs:
      lint:
        parameters:
          chart:
            description: Chart path
            type: string
            default: keep-client
          lint-params:
            description: Params to lint with
            type: string
            default: ""
        docker:
        - image: ajcrowe/docker-helm:latest
        steps:
        - checkout
        - run:
            name: Lint Chart
            command: |
              cd << parameters.chart >>
              helm lint << parameters.lint-params >> .

workflows:
  lint:
    jobs:
    - local/lint:
        name: lint-<< matrix.chart >>
        lint-params: "--strict"
        matrix:
          parameters:
            chart: ["keep-client", "keep-ecdsa"]
    - local/lint:
        name: lint-<< matrix.chart >>-existing-secrets
        lint-params: "--strict -f ../examples/existing-secrets.yaml"
        matrix:
          parameters:
            chart: ["keep-client", "keep-ecdsa"]
    - local/lint:
        name: lint-<< matrix.chart >>-inline-resources
        lint-params: "--strict -f ../examples/inline-resources.yaml"
        matrix:
          parameters:
            chart: ["keep-client", "keep-ecdsa"]
    - local/lint:
        name: lint-<< matrix.chart >>-load-files
        lint-params: "--strict -f ../examples/load-files.yaml"
        matrix:
          parameters:
            chart: ["keep-client", "keep-ecdsa"]
