{{ if not .Values.keyPass.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keep-ecdsa.fullname" . }}-keypass
  labels:
    {{- include "keep-ecdsa.labels" . | nindent 4 }}
type: Opaque
data:
  KEEP_ETHEREUM_PASSWORD: {{ .Values.keyPass.password | b64enc }}
{{- end }}
{{- if not .Values.keyFile.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keep-ecdsa.fullname" . }}-keyfile
  labels:
    {{- include "keep-ecdsa.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.ethereum.keyFile }}: |-
    {{- if .Values.keyFileJson }}
    {{ .Values.keyFileJson | b64enc | nindent 4 }}
    {{- else }}
    {{ .Files.Get .Values.keyFile.localFile | b64enc }}
    {{- end }}
{{- end }}
