apiVersion: v1
kind: Service
metadata:
  name: {{ include "keep-ecdsa.fullname" . }}
  labels:
    {{- include "keep-ecdsa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }}
      protocol: TCP
      name: {{ .Values.service.name }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "keep-ecdsa.selectorLabels" . | nindent 4 }}
