apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "keep-ecdsa.fullname" . }}
  labels:
    {{- include "keep-ecdsa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keep-ecdsa.selectorLabels" . | nindent 6 }}
  serviceName: ""
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "keep-ecdsa.labels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "keep-ecdsa.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.image.command }}
          args:
            - "--config={{ .Values.config.paths.config }}/config.toml"
            - "start"
          {{- if .Values.config.logLevel }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "keep-ecdsa.fullname" . }}-keypass
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.probesEnabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.name }}
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.name }}
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 5
          {{- end }}
          volumeMounts:
            - name: {{ include "keep-ecdsa.fullname" . }}-data
              mountPath: {{ .Values.config.paths.data }}
            - name: config
              mountPath: {{ .Values.config.paths.config }}
            - name: keyfile
              mountPath: {{ .Values.config.paths.keyStore }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "keep-ecdsa.fullname" . }}
        - name: keyfile
          secret:
            {{- if .Values.keyFile.existingSecret }}
            secretName: {{ .Values.keyFile.existingSecret }}
            {{- else }}
            secretName: {{ include "keep-ecdsa.fullname" . }}-keyfile
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "keep-ecdsa.fullname" . }}-data
      spec:
        storageClassName: {{ .Values.persistentDisk.storageClass }}
        accessModes: [ {{ .Values.persistentDisk.accessModes }} ]
        resources:
          requests:
            storage: {{ .Values.persistentDisk.size }}
