replicaCount: 1

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

image:
  command: ["/usr/local/bin/keep-client"]
  repository: keepnetwork/keep-client
  pullPolicy: IfNotPresent
  tag: "v1.2.4-rc"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podLabels: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  name: p2p
  type: ClusterIP
  port: 3919

probesEnabled: false

configYaml: ""
configFile:
  enabled: false
  localFile: config.toml

keyFileJson: ""
keyFile:
  existingSecret: ""
  localFile: wallet.json
keyPass:
  existingSecret: ""
  password: "keepnetworkclient"

config:
  logLevel: ""
  ethereum:
    account: "0x0000000000000000000000000000000000000000"
    url: "wss://ropsten.infura.io/ws/v3/mykey"
    urlRpc: "https://ropsten.infura.io/v3/mykey"
    keyFile: wallet.json
  port: 3919
  contractAddrs:
    KeepRandomBeaconOperator: "0x70F2202D85a4F0Cad36e978976f84E982920A624"
    TokenStaking: "0x6D1140a8c8e6Fac242652F0a5A8171b898c67600"
    KeepRandomBeaconService: "0x17056632d8db5a5c42fdE25132C59DD975a6da7F"
  peers: 
  - '"/dns4/bootstrap-1.core.keep.test.boar.network/tcp/3001/ipfs/16Uiu2HAkuTUKNh6HkfvWBEkftZbqZHPHi3Kak5ZUygAxvsdQ2UgG"'
  - '"/dns4/bootstrap-2.core.keep.test.boar.network/tcp/3001/ipfs/16Uiu2HAmQirGruZBvtbLHr5SDebsYGcq6Djw7ijF3gnkqsdQs3wK"'
  - '"/dns4/bootstrap-3.test.keep.network/tcp/3919/ipfs/16Uiu2HAm8KJX32kr3eYUhDuzwTucSfAfspnjnXNf9veVhB12t6Vf"'
  - '"/dns4/bootstrap-2.test.keep.network/tcp/3919/ipfs/16Uiu2HAmNNuCp45z5bgB8KiTHv1vHTNAVbBgxxtTFGAndageo9Dp"'
  announcedAddrs: 
  - '"/ip4/127.0.0.1/tcp/3919"'
  paths:
    keyStore: /mnt/keystore
    config: /mnt/config
    data: /mnt/persistence

persistentDisk:
  enabled: true
  storageClass: ""
  size: 1Gi
  accessModes: ReadWriteOnce

metrics:
  enabled: false
  port: 8080
  networkMetricsTick: 60
  ethereumMetricsTick: 600

serviceMonitor:
  enabled: false
  additionalLabels: {}
  annotations: {}
  interval: ""
  scrapeTimeout: ""

resources: {}
  #limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
