replicaCount: 1

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

image:
  command: ["/usr/local/bin/keep-client"]
  repository: keepnetwork/keep-client
  pullPolicy: IfNotPresent
  tag: "v1.3.0"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podLabels: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  name: p2p
  type: ClusterIP
  port: 3919

probesEnabled: false

configYaml: ""
configFile:
  enabled: false
  localFile: config.toml

keyFileJson: ""
keyFile:
  existingSecret: ""
  localFile: wallet.json
keyPass:
  existingSecret: ""
  password: "keepnetworkclient"

config:
  logLevel: ""
  ethereum:
    account: "0x0000000000000000000000000000000000000000"
    url: "wss://ropsten.infura.io/ws/v3/mykey"
    urlRpc: "https://ropsten.infura.io/v3/mykey"
    keyFile: wallet.json
  port: 3919
  contractAddrs:
    KeepRandomBeaconOperator: "0xdf708431162ba247ddae362d2c919e0fbafcf9de"
    TokenStaking: "0x1293a54e160d1cd7075487898d65266081a15458"
    KeepRandomBeaconService: "0x50510e691c90ea098e3fdd23c311731bf394aafd"
  peers:
  - '"/dns4/bst-a01.core.keep.boar.network/tcp/3001/ipfs/16Uiu2HAkzYFHsqbwt64ZztWWK1hyeLntRNqWMYFiZjaKu1PZgikN"'
  - '"/dns4/bst-b01.core.keep.boar.network/tcp/3001/ipfs/16Uiu2HAkxLttmh3G8LYzAy1V1g1b3kdukzYskjpvv5DihY4wvx7D"'
  announcedAddrs: 
  - '"/ip4/127.0.0.1/tcp/3919"'
  paths:
    keyStore: /mnt/keystore
    config: /mnt/config
    data: /mnt/persistence

persistentDisk:
  enabled: true
  storageClass: ""
  size: 1Gi
  accessModes: ReadWriteOnce

metrics:
  enabled: false
  port: 8080
  networkMetricsTick: 60
  ethereumMetricsTick: 600

serviceMonitor:
  enabled: false
  additionalLabels: {}
  annotations: {}
  interval: ""
  scrapeTimeout: ""

resources: {}
  #limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
